package bussinesslogic.test.transfer;

import junit.framework.TestCase;
import PO.TeamTechPO;
import bussinesslogic.TeamTech.TeamTechLineItem;
import bussinesslogic.Transfer.P2L.TeamTechP2L;

public class TestTeamTechP2L extends TestCase{
	public void testP2L(){
		TeamTechP2L p2l = new TeamTechP2L();
		TeamTechPO ttpo = new TeamTechPO();
		ttpo.name = "Haha";
		ttpo.season = "13-14";
		ttpo.gameNum = 82;
		ttpo.shotInRate = 1;
		ttpo.threeShotInRate = 2;
		ttpo.penaltyShotInRate = 3;
		ttpo.winningRate = 4;
		ttpo.offensiveEfficiency = 5;
		ttpo.defensiveEfficiency = 6;
		ttpo.reboundEfficiency = 7;
		ttpo.stealEfficiency = 8;
		ttpo.secondaryAttackEfficiency = 9;
		ttpo.winningNum = 10;
		ttpo.shotInNum = 82*11;
		ttpo.shotNum = 82*12;
		ttpo.threeShotInNum = 82*13;
		ttpo.threeShotNum = 82*14;
		ttpo.penaltyShotInNum = 82*15;
		ttpo.penaltyShotNum = 82*16;
		ttpo.offensiveRebound = 82*17;
		ttpo.defensiveRebound = 82*18;
		ttpo.rebound = 82*19;
		ttpo.secondaryAttack = 82*20;
		ttpo.steal = 82*21;
		ttpo.blockShot = 82*22;
		ttpo.fault = 82*23;
		ttpo.foul = 82*24;
		ttpo.score = 82*25;
		ttpo.offensiveRound = 82*26;
		TeamTechLineItem result = p2l.p2l(ttpo);
		TeamTechLineItem expected = new TeamTechLineItem();
		expected.name = "Haha";
		expected.season = "13-14";
		expected.gameNum = 82;
		expected.shotInRate = 1;
		expected.threeShotInRate = 2;
		expected.penaltyShotInRate = 3;
		expected.winningRate = 4;
		expected.offensiveEfficiency = 5;
		expected.defensiveEfficiency = 6;
		expected.reboundEfficiency = 7;
		expected.stealEfficiency = 8;
		expected.secondaryAttackEfficiency = 9;
		expected.winningNum = 10;
		expected.shotInNum = 82*11;
		expected.shotNum = 82*12;
		expected.threeShotInNum = 82*13;
		expected.threeShotNum = 82*14;
		expected.penaltyShotInNum = 82*15;
		expected.penaltyShotNum = 82*16;
		expected.offensiveRebound = 82*17;
		expected.defensiveRebound = 82*18;
		expected.rebound = 82*19;
		expected.secondaryAttack = 82*20;
		expected.steal = 82*21;
		expected.blockShot = 82*22;
		expected.fault = 82*23;
		expected.foul = 82*24;
		expected.score = 82*25;
		expected.offensiveRound = 82*26;
		expected.shotInNumave = 11;
		expected.shotNumave = 12;
		expected.threeShotInNumave = 13;
		expected.threeShotNumave = 14;
		expected.penaltyShotInNumave = 15;
		expected.penaltyShotNumave = 16;
		expected.offensiveReboundave = 17;
		expected.defensiveReboundave = 18;
		expected.reboundave = 19;
		expected.secondaryAttackave = 20;
		expected.stealave = 21;
		expected.blockShotave = 22;
		expected.faultave = 23;
		expected.foulave = 24;
		expected.scoreave = 25;
		expected.offensiveRoundave = 26;
		boolean test = expected.equals(result);
		assertTrue("tell me WHY!",test);
	}
}
