package bussinesslogic.test.transfer;

import junit.framework.TestCase;
import VO.TeamTechVO;
import bussinesslogic.TeamTech.TeamTechLineItem;
import bussinesslogic.Transfer.V2L.TeamTechV2L;

public class TestTeamTechV2L extends TestCase{
	public void testV2L(){
		TeamTechV2L v2l = new TeamTechV2L();
		TeamTechVO ttvo = new TeamTechVO();
		ttvo.name = "Haha";
		ttvo.season = "13-14";
		ttvo.gameNum = 82;
		ttvo.shotInRate = 1;
		ttvo.threeShotInRate = 2;
		ttvo.penaltyShotInRate = 3;
		ttvo.winningRate = 4;
		ttvo.offensiveEfficiency = 5;
		ttvo.defensiveEfficiency = 6;
		ttvo.reboundEfficiency = 7;
		ttvo.stealEfficiency = 8;
		ttvo.secondaryAttackEfficiency = 9;
		ttvo.winningNum = 10;
		ttvo.shotInNum = 82*11;
		ttvo.shotNum = 82*12;
		ttvo.threeShotInNum = 82*13;
		ttvo.threeShotNum = 82*14;
		ttvo.penaltyShotInNum = 82*15;
		ttvo.penaltyShotNum = 82*16;
		ttvo.offensiveRebound = 82*17;
		ttvo.defensiveRebound = 82*18;
		ttvo.rebound = 82*19;
		ttvo.secondaryAttack = 82*20;
		ttvo.steal = 82*21;
		ttvo.blockShot = 82*22;
		ttvo.fault = 82*23;
		ttvo.foul = 82*24;
		ttvo.score = 82*25;
		ttvo.offensiveRound = 82*26;
		ttvo.shotInNumave = 11;
		ttvo.shotNumave = 12;
		ttvo.threeShotInNumave = 13;
		ttvo.threeShotNumave = 14;
		ttvo.penaltyShotInNumave = 15;
		ttvo.penaltyShotNumave = 16;
		ttvo.offensiveReboundave = 17;
		ttvo.defensiveReboundave = 18;
		ttvo.reboundave = 19;
		ttvo.secondaryAttackave = 20;
		ttvo.stealave = 21;
		ttvo.blockShotave = 22;
		ttvo.faultave = 23;
		ttvo.foulave = 24;
		ttvo.scoreave = 25;
		ttvo.offensiveRoundave = 26;
		TeamTechLineItem result = v2l.v2l(ttvo);
		TeamTechLineItem expected = new TeamTechLineItem();
		expected.name = "Haha";
		expected.season = "13-14";
		expected.gameNum = 82;
		expected.shotInRate = 1;
		expected.threeShotInRate = 2;
		expected.penaltyShotInRate = 3;
		expected.winningRate = 4;
		expected.offensiveEfficiency = 5;
		expected.defensiveEfficiency = 6;
		expected.reboundEfficiency = 7;
		expected.stealEfficiency = 8;
		expected.secondaryAttackEfficiency = 9;
		expected.winningNum = 10;
		expected.shotInNum = 82*11;
		expected.shotNum = 82*12;
		expected.threeShotInNum = 82*13;
		expected.threeShotNum = 82*14;
		expected.penaltyShotInNum = 82*15;
		expected.penaltyShotNum = 82*16;
		expected.offensiveRebound = 82*17;
		expected.defensiveRebound = 82*18;
		expected.rebound = 82*19;
		expected.secondaryAttack = 82*20;
		expected.steal = 82*21;
		expected.blockShot = 82*22;
		expected.fault = 82*23;
		expected.foul = 82*24;
		expected.score = 82*25;
		expected.offensiveRound = 82*26;
		expected.shotInNumave = 11;
		expected.shotNumave = 12;
		expected.threeShotInNumave = 13;
		expected.threeShotNumave = 14;
		expected.penaltyShotInNumave = 15;
		expected.penaltyShotNumave = 16;
		expected.offensiveReboundave = 17;
		expected.defensiveReboundave = 18;
		expected.reboundave = 19;
		expected.secondaryAttackave = 20;
		expected.stealave = 21;
		expected.blockShotave = 22;
		expected.faultave = 23;
		expected.foulave = 24;
		expected.scoreave = 25;
		expected.offensiveRoundave = 26;
		boolean test = expected.equals(result);
		assertTrue("tell me WHY!",test);
	}
}
